name: SingleTimestampsRecognition
channels:
  - defaults
dependencies:
  - matplotlib
  - natsort
  - numpy
  - pandas
  - pip
  - pytorch=0.3.1
  - python=3.6.8
  - pyyaml
  - scikit-learn
  - torchvision=0.2.0
  - tqdm
  - yaml
  - pip:
    - tensorboardx==1.2
